---
# tasks file for osp_security
- os_security_group:
    cloud: ospcloud
    state: present
    name: sg_"{{ item.value.metadata.group }}"
    description: security group for security gorup 'sg_"{{ item.value.metadata.group }}"'
  with_dict: "{{ instance }}"

- os_security_group_rule:
    cloud: ospcloud
    security_group: sg_"{{ item.0.metadata.group }}"
    protocol: "{{ item.1.protocol }}"
    port_range_min: "{{ item.1.ports }}"
    port_range_max: "{{ item.1.ports }}"
    remote_ip_prefix: 0.0.0.0/0
  with_subelements: 
   - "{{ instance }}"
   -  ports_open 
