---
# tasks file for win_service_config
- name: Windows service start
  win_service:
    name: "{{ service_name }}"
    state: started
    start_mode: auto
    enabled: yes
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"
