---
# tasks file for ssh_keys
- name: Creating the key pair
  user:
     name: "{{ ansible_env.USER }}"
     generate_ssh_key: yes
     ssh_key_file: "{{ ansible_env.HOME }}/.ssh/openstack_id_rsa"

- name: generating the key pair 
  os_keypair:
      cloud: ospcloud
      state: present
      name: ansible_ssh
      public_key_file: "{{ ansible_env.HOME }}/.ssh/openstack_id_rsa.pub"
